# Generated by Django 4.0.3 on 2022-03-04 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='portrait',
            field=models.ImageField(default='hero_portraits/placeholderPortrait.jpg', upload_to='hero_portraits/'),
        ),
    ]
